branch-defaults:
  master:
    environment: ${CIRCLE_BRANCH}-surfswap-be
global:
  application_name: surfswap
  default_ec2_keyname: XXXXXX
  default_platform: Java 8 running on 64bit Amazon Linux/2.9.1
  default_region: eu-central-1
  sc: git