version: 2.0
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello Surfswap app!'
            echo 'This is the delivery pipeline'
      - run:
          name: Maven clean install
          command: |
            mvn clean install